version: "3.9"

networks:
  music_theory_network:
    driver: bridge

services:
  php:
    build: ./docker/php
    container_name: music_theory_php
    volumes:
      - .:/var/www
    networks:
      - music_theory_network
  nginx:
    image: nginx:alpine
    container_name: music_theory_nginx
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - music_theory_network
  # mysql:
  #   image: mysql:8.0
  #   container_name: music_theory_mysql
